// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cfBm2bHBC8PGFSr3Vzfj0cj3klWD5dc',
    appId: '1:600975835841:web:31655af872210e407a0a40',
    messagingSenderId: '600975835841',
    projectId: 'auth-1868c',
    authDomain: 'auth-1868c.firebaseapp.com',
    storageBucket: 'auth-1868c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5MFL7ZF97EekRUs1b1RUNzFq7lwz4c0',
    appId: '1:600975835841:android:106cb0acf49c63e77a0a40',
    messagingSenderId: '600975835841',
    projectId: 'auth-1868c',
    storageBucket: 'auth-1868c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDw9HVaTt23agDMtbICLBPfgFnu9D1LHE',
    appId: '1:600975835841:ios:119742ce6b4af2b87a0a40',
    messagingSenderId: '600975835841',
    projectId: 'auth-1868c',
    storageBucket: 'auth-1868c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDw9HVaTt23agDMtbICLBPfgFnu9D1LHE',
    appId: '1:600975835841:ios:119742ce6b4af2b87a0a40',
    messagingSenderId: '600975835841',
    projectId: 'auth-1868c',
    storageBucket: 'auth-1868c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2cfBm2bHBC8PGFSr3Vzfj0cj3klWD5dc',
    appId: '1:600975835841:web:ee8e245f037f3f587a0a40',
    messagingSenderId: '600975835841',
    projectId: 'auth-1868c',
    authDomain: 'auth-1868c.firebaseapp.com',
    storageBucket: 'auth-1868c.firebasestorage.app',
  );
}
